ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(100);

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20);

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'accepted';

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
